name: deepshield
description: DeepShield - mobile-first deepfake detection
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0

  # --- Firebase + Google Sign-In ---
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_auth: ^6.1.0
  google_sign_in: ^5.4.0

  # Animations
  flutter_animate: ^4.5.0

  # Optional / Premium
  in_app_purchase: ^3.2.3
  flutter_launcher_icons: ^0.14.4

  # --- Localization ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - .env
    - assets/icon/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

# --- Localization config must be TOP LEVEL, not under flutter: ---
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales: [en, hi, bn, ta, te, ml, kn, mr]
