name: deepshield
description: DeepShield - mobile-first deepfake detection
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  image_picker: ^1.2.0
  flutter_image_compress: ^2.1.0
  # flutter_video_compress: ^0.3.8
  path_provider: ^2.0.15
  path: ^1.8.3
  shared_preferences: ^2.1.1
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
